[package]
name = "google-classroom"
version = "0.0.1"
edition = "2021"

[features]
default = []
chrono = ["chrono"]

[dependencies]
serde = { version = "1", features = ["derive"] }
reqwest = { version = "0.11" }
chrono = { version = "0.4.23", optional = true }

